---
deployment:
 tasks:
 - export DEPLOYPATH=/home/begawanp/public_html/begawanpolosoro.com/
 - cp .htaccess $DEPLOYPATH
 - cp -r ./application/models ./application/$DEPLOYPATH
 - cp -r ./application/views ./application/$DEPLOYPATH
 - cp -r ./application/controllers ./application/$DEPLOYPATH 
 - cp -r ./uploads $DEPLOYPATH 

 - /usr/bin/rsync -Paz * $DEPLOYPATH --delete