---
deployment:
 tasks:
 - export DEPLOYPATH=/home/begawanp/public_html/begawanpolosoro.com/
 - cp .htaccess $DEPLOYPATH
 - cp -r ./application/models $DEPLOYPATH
 - cp -r ./application/views $DEPLOYPATH
 - cp -r ./application/controllers $DEPLOYPATH 
 - cp -r ./uploads $DEPLOYPATH 

 - /usr/bin/rsync -Paz * $DEPLOYPATH --delete