---
deployment:
 tasks:
 - export DEPLOYPATH=/home/begawanp/public_html/begawanpolosoro.com/
 - export APPPATH=/home/begawanp/public_html/begawanpolosoro.com/application/
 - cp .htaccess $DEPLOYPATH
 - cp -r ./application/models $APPPATH
 - cp -r ./application/views $APPPATH
 - cp -r ./application/controllers $APPPATH 
 - cp -r ./application/third_party $APPPATH

 - /usr/bin/rsync -Paz * $DEPLOYPATH --delete