version: '3'
services:

  nginx:
    image: nginx:latest
    platform: linux/x86_64
    volumes:
      - ./:/public
      - ./site-conf.conf:/etc/nginx/conf.d/default.conf
    networks: 
      codeigniter_net:
    ports:
      - "8080:90"
    restart: always

  php:
    build: 
      context: .
    volumes:
      - ./:/public
    platform: linux/x86_64
    networks:
      codeigniter_net:

networks:
  codeigniter_net: